export { default as LandingPage } from "./LandingPage";
export { default as OurStaff } from "./OurStaffPage";
export { default as LoginPage } from "./LoginPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as Dashboard} from "./Dashboard";
export {default as Students} from "./Students";
export {default as Student} from "./Student";
export {default as Teachers} from "./Teachers";
export {default as ClassRooms} from "./Classrooms";
export {default as Calendars} from "./Calendars";
export {default as Grades} from "./Grades";
export {default as Rewards} from "./Rewards";
export {default as TeacherReview} from "./TeacherReview";
export {default as Chats} from "./Chats";