version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  api:
    depends_on:
      - mysqldb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - ES_HOST=elasticsearch
    networks:
      - backend
      - frontend

  app:
    depends_on:
      - api
    build: ./app
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes: 
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.107 #change it according to your Local IP Address
    networks:
      - frontend  

  webapp:
    build: ./webapp
    container_name: webapp_c
    ports: 
      - '3000:3000'
    volumes: 
      - ./webapp:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    restart: always
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - api
    networks:
      - backend
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - backend

volumes: 
  db:

networks:
  backend:
  frontend: